name: Java CI with Mave #là tương đương Console.log ghi lại nhật kí chạy các lệnh 

on:
  push:
    branches: [ "main" ]  #bất kì ai push code lên hàm main or hàm code chính
  pull_request:
    branches: [ "main" ]

jobs:                        #thì tự động thực thi các lệnh dưới đây 
  build:                     #build app -> .jar .war bằng cách 
                            #1. dùng server bên mỹ, cài sẵn giùm OS Uburtu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      #2. có server rồi, download code từ github về server này 
    - name: Set up JDK 21 - Mượn JDK 21       #3. cho mượn cái JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'            #4. khai báo version JDK tương ứng với pom.xml
        distribution: 'temurin'       #5. mượn maven, chạy lệnh đóng gói, test luôn xanh đỏ
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
